### ISSUE TITLE
Use Denoify under the hood 

### ISSUE THREAD

**Issue by garronej** [bevry/make-deno-edition#63]
Hi @balupton,  

I am the author of [Denoify](https://github.com/garronej/denoify).  

I like edition, it's a nice tool! I think it is cool to be able to add deno target to a project using edition.
However I don't see the need for an other implementation of the transpiler, why not use Denoify under the hood?
Beside the fact that Denoify is more mature and feature rich than `make-deno-edition` I see a glaring issue in the current implementation of your transpiler that is a ticking time bomb. When the polyfills  from `deno.land/std/node` are injected the version is not freezed it is always the latest version that is fetched. This mean that the code of your users can break any minute.  

On my hand I can enable Denoify to support module that have a Deno edition  on NPM to be supported out of the box.  

What do you think?

**Comment by balupton** [comment]
I'd definitely like to see more things support the `packge.json:deno` and package.json:editions` fields, as that would increase compatibility with a larger array of packages. So 👍 there.

---

For the transpiler, `make-deno-edition`, `filedirname`, and my work on `std/node` have all been done to meet the needs of our Bevry packages. Many of the todos for `make-deno-edition` are minor things.

---

Re the "glaring issue", I'll make an issue for it to become an option, as older `std/node` libs may not work on new deno versions, so pinning versions as you suggest also carries the same risk of breaking things. Instead, I consider it much safer and more preferable to use the latest `std/node` as the operating assumption:

- newer `std/node` will be more compatible with the versions of Deno the user is running
- newer `std/node` will be more compatible as a polyfill for Node.js

As I've written many of the `std/node` utilities myself, I know this to be the cast for both items. Old `std/node` libraries break on new Deno versions, and old `std/node` libraries are less compatible with Node.js.

Sure, we could assume then that a package version, such as what `make-deno-edition` is generated on, can be pinned to certain versions, and that is precisely what the Edition standard and autoloader is designed to enable seamlessly, however that too is a minor improvement, that would take minimal time when it is necessary. 

Certainly an option for pinning, or using latest, is certainly preferable to either assumption; an option would also be a minimal change.

---

I think there is enough room for multiple transpiler strategies, as there are different assumptions going in.

**Comment by garronej** [comment]
ok lol

**Comment by garronej** [comment]
@balupton  Sorry for that answer. 😔 It was late and I was on hinge.  
Reading back at my initial message, I understand how it must have come out as condescending, my apologies for that as well.  
And thank you for your work on `std/node`, Denoify benefit from it.  🙏🏼
I see your point, if the thing does the job you need it to do then it is mature and I understand your will to keep control over the assumptions that are made.   
It was however in good faith that I suggested that you use Denoify.  
It has features that make it easier support third-party modules and to circumvent the missing node builtins.  
I thought you might have been interested but if you’re not you’re not, I have no business arguing it.  

Respectfully 🙂

**Comment by balupton** [comment]
@garronej no worries, good will to you too. I hope the best for Denoify as well
